# Generated by Django 5.0.6 on 2024-06-26 05:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("materials", "0002_course_owner_lesson_owner"),
        ("users", "0002_payment"),
    ]

    operations = [
        migrations.AlterField(
            model_name="payment",
            name="paid_lesson",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="materials.lesson",
                verbose_name="Оплаченный урок",
            ),
        ),
    ]
